// Code generated by MockGen. DO NOT EDIT.
// Source: poke.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	api "pokedex-clone/internal/api"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPokeAPI is a mock of PokeAPI interface.
type MockPokeAPI struct {
	ctrl     *gomock.Controller
	recorder *MockPokeAPIMockRecorder
}

// MockPokeAPIMockRecorder is the mock recorder for MockPokeAPI.
type MockPokeAPIMockRecorder struct {
	mock *MockPokeAPI
}

// NewMockPokeAPI creates a new mock instance.
func NewMockPokeAPI(ctrl *gomock.Controller) *MockPokeAPI {
	mock := &MockPokeAPI{ctrl: ctrl}
	mock.recorder = &MockPokeAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPokeAPI) EXPECT() *MockPokeAPIMockRecorder {
	return m.recorder
}

// GetSpecies mocks base method.
func (m *MockPokeAPI) GetSpecies(ctx context.Context, name string) (*api.PokemonSpecies, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpecies", ctx, name)
	ret0, _ := ret[0].(*api.PokemonSpecies)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpecies indicates an expected call of GetSpecies.
func (mr *MockPokeAPIMockRecorder) GetSpecies(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpecies", reflect.TypeOf((*MockPokeAPI)(nil).GetSpecies), ctx, name)
}
